### ISSUE TITLE
进度改变

### ISSUE THREAD

**Issue by sugar0811** [a483210/PicturePlayerView#1]
目前在研究您写的这个图片播放器,想要做进度的一个可拖动，目前来说好像是没有的，代码还没看透，能否提供一些改变进度的着手点.

**Comment by a483210** [comment]
额，你可以先看下我写的这篇[文章](http://www.jianshu.com/p/53f9bd1fa1a6)，然后你说的可拖动关键点在[Scheduler.java](https://github.com/a483210/PicturePlayerView/blob/master/pictureplayerview/src/main/java/com/xiuyukeji/scheduler/Scheduler.java)的mFrameIndex，有时间我可以研究下。

**Comment by a483210** [comment]
顺便问下，你说的进度拖动需要实时浏览吗？（在拖动中浏览帧），如果是实现起来就麻烦了一些。

**Comment by sugar0811** [comment]
非常感谢您的回复，我觉得可以一步步完善，先不用做实时拖动浏览。

**Comment by a483210** [comment]
代码已经提交上传了，[Seek方法](https://github.com/a483210/PicturePlayerView/blob/master/pictureplayerview/src/main/java/com/xiuyukeji/pictureplayerview/PicturePlayerView.java#L218-L225)，你可以参考下。

**Comment by sugar0811** [comment]
太牛了，非常感谢！！  方便留个联系方式交流吗？QQ之类的.

**Comment by sugar0811** [comment]
有报错  各种变量找不到 麻烦看一下什么原因

**Comment by sugar0811** [comment]
对照之前的项目把变量加上之后恢复，测试seek可用  谢谢

**Comment by a483210** [comment]
额，你有什么问题，直接简书信息发我，或者这里提就好了

**Comment by sugar0811** [comment]
好的，再请教一个问题，目前暂停时seek到某个位置只有点击播放后才能看到seek后的画面，可不可以在暂停状态下seek后可以立即看到seek后的那个位置那一帧的画面，状态还是暂停，就像市面上大部分的视频播放器一样,改了一下您的源码，发现还是各种问题，如果您能指点一下或者帮忙完善一下更好了.

**Comment by a483210** [comment]
我这可能暂时没时间，如果要修改就需要在mScheduler.seek(frameIndex);完成之后开启一个任务，等待图片读取完成后在调用PictureRenderer.draw绘制。

**Comment by sugar0811** [comment]
是的，我现在遇到的问题就是seek到某一帧的时候马上去画，发现内存和复用池里面都没有，bitmap为null,然后到了下一帧就读到了可以显示了.比如seek到150帧马上去画,画面没有变化，因为bitmap为null,再执行一下next到151就有了.

**Comment by a483210** [comment]
因为seek后我清空了缓存图片，所以马上去绘制肯定是空的，你必须要等待read线程读取到当前帧后才能去绘制。

**Comment by sugar0811** [comment]
实际上您的demo在播放时去seek到某帧的时候也是null的，也是从后一帧开始绘制的。比如在播放状态下,seek到100，实际上100也是null的，并没有被绘制到频幕上，您也是从101开始绘制的

**Comment by sugar0811** [comment]
我现在的问题在于如何去等待这个read线程读取到seek后的当前帧呢？指点一下

**Comment by a483210** [comment]
当前在播放的情况下，如果seek的确会从下一帧播放起，之前写的快了，没考虑到，如果要修改，可以把
[代码](https://github.com/a483210/PicturePlayerView/blob/master/pictureplayerview/src/main/java/com/xiuyukeji/pictureplayerview/PicturePlayer.java#L139-L143)
```
        mScheduler.seekTo(frameIndex);

        if (!isPaused) {
            resume();
        }
```
这段代码放到readThread下，记录一个标准位，当读取到当前帧的时候再去绘制。

**Comment by sugar0811** [comment]
这段代码加到readThread下实际上还是有问题的，不知道是不是我改得有问题。我目前想实现我上述过的需求的话是一个临时方案了，就是在onFrameUpdate里的回调去绘制的时候发现bitmap为null的话就去磁盘里面读取源数据,加入到cacheList里，这样的话那一帧的绘制空白能填补，就是不知道会不会有什么后遗症，目前测试的话效果还是很明显的.

**Comment by a483210** [comment]
其实你可以直接在seek里面读取那一帧，然后在开始，只不过seek可能要阻塞几毫秒，事实上目前我还没想到在不修改现在代码的基础上如何去比较好的修复它。

**Comment by sugar0811** [comment]
大神如果想到更好的解决方案可以更新一波哦，顺便做一下拖动时画面实时浏览吧。辛苦了。您的这个项目相对lottie还是有优势的，lottie对本地图片还需要json文件支持，可能更高效但是多做一步很头疼。我现在还在您的基础上做播放时的时候画面可放大缩小，以及实时更改图片对比度(设置paint),有空可以完善一下哈，期待您的更新。

**Comment by a483210** [comment]
放大缩小和更改图片对比度是什么个操作？

**Comment by sugar0811** [comment]
就像微信里面点开一张图片可以手势放大和缩小，查看局部图像。更改对比度的话因为我们这边图片都是黑白的，用户可能需要查看更清晰的话需要更改黑白对比度，便于观看。

**Comment by a483210** [comment]
为什么播放器要手势放大和缩小呢。。。好奇怪的需求，而且这个功能去直接对View调用setScaleX和setScaleY不就好了么

**Comment by sugar0811** [comment]
您好，好久不见。用您的库改造后的功能模块快上线了，今天发现了一个小问题，弄得我很苦恼，在Activity  oncreate | onresume就start时，有时候绘制第一帧时PictureRenderer onDraw函数中 mTextureView.lockCanvas()会返回null,第一帧未显示在界面上。报错日志显示 lock failed  already locked....请问您知道原因或者解决办法吗？

**Comment by a483210** [comment]
如果surface没有初始化出来肯定是空，onresume后应该是不会的，你到底是要实现什么功能，你说下，我看下。
