### ISSUE TITLE
播放动画一段时间后，崩溃

### ISSUE THREAD

**Issue by liuyao0305** [a483210/PicturePlayerView#3]
每次调用 start函数都会调用以下函数
   mFrameThread = new FrameThread("scheduler");
   mFrameThread.start();
重复调用会申请不到FramThread

**Comment by a483210** [comment]
PicturePlayerView目前存在一些bug，我没有时间去修改，如果你是要做类似直播间动画我建议采用animated webp的方式，然后用fresco播放
